import requests
import sys

def check_health(url="http://localhost:8081"):
    print(f"Checking health of {url}...")
    try:
        # Check Metrics
        resp_met = requests.get(f"{url}/metrics", timeout=5)
        if resp_met.status_code == 200:
            print("[PASS] /metrics endpoint is up.")
        else:
            print(f"[FAIL] /metrics returned {resp_met.status_code}")
            return False

        # Check Docs (auto-generated by FastAPI)
        resp_docs = requests.get(f"{url}/docs", timeout=5)
        if resp_docs.status_code == 200:
            print("[PASS] /docs endpoint is up.")
        else:
            print(f"[FAIL] /docs returned {resp_docs.status_code}")
            return False
            
        print("Server appears healthy.")
        return True
    except Exception as e:
        print(f"[FAIL] Connection error: {e}")
        return False

if __name__ == "__main__":
    success = check_health()
    sys.exit(0 if success else 1)
